In [139]:
import pandas as pd

In [140]:
df = pd.read_csv('Datasets\Banking Customer Churn Prediction Datasets.csv')

<>:1: SyntaxWarning: invalid escape sequence '\B'
<>:1: SyntaxWarning: invalid escape sequence '\B'
C:\Users\DELL\AppData\Local\Temp\ipykernel_6388\2650144982.py:1: SyntaxWarning: invalid escape sequence '\B'
  df = pd.read_csv('Datasets\Banking Customer Churn Prediction Datasets.csv')

In [141]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [143]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [144]:
df.duplicated().sum()

np.int64(0)

In [145]:
df =  df.drop(['RowNumber','CustomerId','Surname'], axis=1)

In [146]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [147]:
df.corr(numeric_only=True)*100

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
CreditScore,100.000000,-0.396491,0.084194,0.626838,1.223788,-0.545848,2.565132,-0.138429,-2.709354
Age,-0.396491,100.000000,-0.999683,2.830837,-3.068009,-1.172103,8.547215,-0.720104,28.532304
Tenure,0.084194,-0.999683,100.000000,-1.225393,1.344376,2.258287,-2.836208,0.778383,-1.400061
Balance,0.626838,2.830837,-1.225393,100.000000,-30.417974,-1.485834,-1.008410,1.279750,11.853277
NumOfProducts,1.223788,-3.068009,1.344376,-30.417974,100.000000,0.318315,0.961188,1.420420,-4.781986
HasCrCard,-0.545848,-1.172103,2.258287,-1.485834,0.318315,100.000000,-1.186564,-0.993341,-0.713777
IsActiveMember,2.565132,8.547215,-2.836208,-1.008410,0.961188,-1.186564,100.000000,-1.142143,-15.612828
EstimatedSalary,-0.138429,-0.720104,0.778383,1.279750,1.420420,-0.993341,-1.142143,100.000000,1.209686
Exited,-2.709354,28.532304,-1.400061,11.853277,-4.781986,-0.713777,-15.612828,1.209686,100.000000

In [148]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [149]:
x = df.drop('Exited', axis=1)
y = df['Exited']

In [150]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

In [151]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [152]:
x_train

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
9254,686,France,Male,32,6,0.00,2,1,1,179093.26
1561,632,Germany,Male,42,4,119624.60,2,1,1,195978.86
1670,559,Spain,Male,24,3,114739.92,1,1,0,85891.02
6087,561,France,Female,27,9,135637.00,1,1,0,153080.40
6669,517,France,Male,56,9,142147.32,1,0,0,39488.04
...,...,...,...,...,...,...,...,...,...,...
5734,768,France,Male,54,8,69712.74,1,1,1,69381.05
5191,682,France,Female,58,1,0.00,1,1,1,706.50
5390,735,France,Female,38,1,0.00,3,0,0,92220.12
860,667,France,Male,43,8,190227.46,1,1,0,97508.04
7270,697,Germany,Male,51,1,147910.30,1,1,1,53581.14

In [153]:
numeric_features = x_train.select_dtypes(include=['int64', 'float64']).columns
categorical_features = x.select_dtypes(include=['object']).columns

In [154]:
categorical_features

Index(['Geography', 'Gender'], dtype='object')

In [155]:
transformer = ColumnTransformer(
    transformers=[
    ('sc',StandardScaler(),numeric_features),
    ('ohe',OneHotEncoder(sparse_output=False,drop='first'),categorical_features),
])

In [156]:
rf = RandomForestClassifier(class_weight='balanced')

In [157]:
pipe  = Pipeline([
    ('trf',transformer),
    ('rf',rf)
])

In [158]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('trf',
                 ColumnTransformer(transformers=[('sc', StandardScaler(),
                                                  Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary'],
      dtype='object')),
                                                 ('ohe',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  Index(['Geography', 'Gender'], dtype='object'))])),
                ('rf', RandomForestClassifier(class_weight='balanced'))])

In [159]:
y_pred = pipe.predict(x_test)

In [160]:
accuracy_score(y_test,y_pred) * 100

86.9

In [161]:
print(pipe.score(x_train,y_train) * 100)
print(pipe.score(x_test,y_test) * 100)

100.0
86.9

In [162]:
from sklearn.metrics import classification_report

In [163]:
# Step 5: Generate and print the classification report
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.88      0.97      0.92      1607
           1       0.78      0.46      0.58       393

    accuracy                           0.87      2000
   macro avg       0.83      0.71      0.75      2000
weighted avg       0.86      0.87      0.86      2000