In [40]:
import pandas as pd

In [41]:
df = pd.read_csv('Datasets\Banking Customer Churn Prediction Datasets.csv')

<>:1: SyntaxWarning: invalid escape sequence '\B'
<>:1: SyntaxWarning: invalid escape sequence '\B'
C:\Users\DELL\AppData\Local\Temp\ipykernel_6720\2650144982.py:1: SyntaxWarning: invalid escape sequence '\B'
  df = pd.read_csv('Datasets\Banking Customer Churn Prediction Datasets.csv')

In [42]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [44]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [45]:
df.duplicated().sum()

np.int64(0)

In [46]:
df.corr(numeric_only=True)*100

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
RowNumber,100.000000,0.420179,0.584016,0.078261,-0.649474,-0.906669,0.724625,0.059875,1.204439,-0.598846,-1.657137
CustomerId,0.420179,100.000000,0.530790,0.949687,-1.488255,-1.241870,1.697188,-1.402513,0.166496,1.527068,-0.624799
CreditScore,0.584016,0.530790,100.000000,-0.396491,0.084194,0.626838,1.223788,-0.545848,2.565132,-0.138429,-2.709354
Age,0.078261,0.949687,-0.396491,100.000000,-0.999683,2.830837,-3.068009,-1.172103,8.547215,-0.720104,28.532304
Tenure,-0.649474,-1.488255,0.084194,-0.999683,100.000000,-1.225393,1.344376,2.258287,-2.836208,0.778383,-1.400061
Balance,-0.906669,-1.241870,0.626838,2.830837,-1.225393,100.000000,-30.417974,-1.485834,-1.008410,1.279750,11.853277
NumOfProducts,0.724625,1.697188,1.223788,-3.068009,1.344376,-30.417974,100.000000,0.318315,0.961188,1.420420,-4.781986
HasCrCard,0.059875,-1.402513,-0.545848,-1.172103,2.258287,-1.485834,0.318315,100.000000,-1.186564,-0.993341,-0.713777
IsActiveMember,1.204439,0.166496,2.565132,8.547215,-2.836208,-1.008410,0.961188,-1.186564,100.000000,-1.142143,-15.612828
EstimatedSalary,-0.598846,1.527068,-0.138429,-0.720104,0.778383,1.279750,1.420420,-0.993341,-1.142143,100.000000,1.209686
Exited,-1.657137,-0.624799,-2.709354,28.532304,-1.400061,11.853277,-4.781986,-0.713777,-15.612828,1.209686,100.000000

In [47]:
df =  df.drop(['RowNumber','CustomerId','Surname'], axis=1)

In [49]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0